packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^2.27.3
    '@antfu/ni': ^24.4.0
    '@antfu/utils': ^9.2.0
    '@types/node': ^20.19.1
    bumpp: ^9.11.1
    eslint: ^9.29.0
    esno: ^4.8.0
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.3
    unbuild: ^2.0.0
    vite: ^5.4.19
    vitest: ^1.6.1
    sass: ^1.89.2
    '@types/fs-extra': ^11.0.4
    fs-extra: ^11.3.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
